### ISSUE TITLE
Spell with save only shows damage button

### ISSUE THREAD

**Issue by trioderegion** [schultzcole/FVTT-Minimal-Rolling-Enhancements-DND5E#12]
Using Hold Person as an example. It has a save, but no direct damage component to the spell. When the "damage" button is clicked, a ui error states that there is no "Primary" damage group.

![image](https://user-images.githubusercontent.com/14878515/104980499-aa4c5480-59d4-11eb-9bd4-c7f2dfef123c.png)

**Comment by trioderegion** [comment]
Related, likely. The same occurs with "Other Formula" only items.

**Comment by schultzcole** [comment]
Yeah, I've got a solution that should cover any item that doesn't have any damage formulae. But thanks for calling that out. I'll be sure to test it out with an item that only has an other formula

**Comment by schultzcole** [comment]
Should be resolved in 0.1.3 which is available now.

@trioderegion
