### ISSUE TITLE
Add setting to revert dialog behavior to core?

### ISSUE THREAD

**Issue by jessev14** [schultzcole/FVTT-Minimal-Rolling-Enhancements-DND5E#14]
I think an additional option under "Show Roll Dialog Modifier" titled something like "Default" or "Core" that reverts the roll dialog behavior back to the core behavior would be nice and also more in line with the "minimal" theme of the module.

**Comment by GvosRamsey** [comment]
Yes, an option to have the roll dialog pop up as default on click would be very useful (attack and damage rolls.)  The modifier keys could be a bit cumbersome for some players.  Thank you.

**Comment by schultzcole** [comment]
Yeah, I'll consider adding a setting for that. Would it be better for that to be a client-side setting or a world setting?

**Comment by GvosRamsey** [comment]
I think both? But client side would be more useful if it's one or the other.

**Comment by jessev14** [comment]
I think the way you have it set up for the other options is best. Let the GM set it as the world default, then let the players change it if they want to.

**Comment by schultzcole** [comment]
This setting has been added in 1.0.1
