### ISSUE TITLE
BUG: Damage Button Appears Above Attack Button

### ISSUE THREAD

**Issue by jessev14** [schultzcole/FVTT-Minimal-Rolling-Enhancements-DND5E#15]
core 0.7.9, dnd5e v1.2.4. No other modules enabled. New test-PC and test-weapon created. Default module settings (i.e. no automatic rolling).

[Actor and Item JSONs.](https://github.com/schultzcole/FVTT-Minimal-Rolling-Enhancements-DND5E/files/5863377/export.zip)

![image](https://user-images.githubusercontent.com/68755874/105645855-5cb76800-5e6a-11eb-9eff-576aecd5d1ae.png)

**Comment by schultzcole** [comment]
Fixed in 1.0.1
