### ISSUE TITLE
Automatically roll item checks causes no chat card output sometimes

### ISSUE THREAD

**Issue by trioderegion** [schultzcole/FVTT-Minimal-Rolling-Enhancements-DND5E#16]
With "Automatically Roll Item Checks" enabled, items without attack rolls (such as saving throw spells), produce no output in chat.

To reproduce, cast "Fire Bolt" from the SRD spells (it has an attack roll) -- a chat card with the roll and damage buttons are output.  Then cast "Mage Hand" and note that a chat card is not produced.

Disable auto roll item checks and both spells output as expected.

**Comment by schultzcole** [comment]
Fixed in 1.0.2
