### ISSUE TITLE
New feature, autocheck targeted AC for attacks

### ISSUE THREAD

**Issue by SergioCaptio** [schultzcole/FVTT-Minimal-Rolling-Enhancements-DND5E#18]
Hi,
I like the simplicity of your module compared to the others. However I love and find extremely time saving the feature present in Pathfinder 2e quick roll that automatically compare the roll with the targeted token AC. I looked into the code and brutally added a few line in the first place it seems to work to get the message that the target was hit, it's 3 line long and with a bit of polish it could be a nice option in this module.
Note that all other roller doesn't have this feature, the only one that does somethings similar is the super - automator and overcomplicated mqol that autochecks and autoroll damage, but prompt nothing and to chat and as a master you know that the targeted creature has some bonuses or ...

in item-base-roll-patch.js inside the  ___createWeaponTitle(item, roll)_ 
```_
      // CUSTOM COMPARE AC PART
	game.user.targets.forEach(t => { 
             if (roll._total >= t.actor.data.data.attributes.ac.value) {title += '<br> ✔️ ' + t.actor.data.name}
             if (roll._total < t.actor.data.data.attributes.ac.value) {title += '<br> ❌ ' + t.actor.data.name}	
        })
    return title;
```

**Comment by schultzcole** [comment]
No, sorry, I don't intend on adding that level of automation to MRE. Feel free to use your alteration in your own games.
