### ISSUE TITLE
Grab bag of 0.8.6 issues :)

### ISSUE THREAD

**Issue by unsoluble** [schultzcole/FVTT-Minimal-Rolling-Enhancements-DND5E#21]
- Attack rolls with either `Skip` or `Show` roll fine, but with deprecation warnings (re `Item#_data` and `Document#_id`).
- Rolling the `Damage` button on any attack card nets a `actor.getOwnedItem is not a function`.
- `Automatically Roll Item Checks` causes all item rolls to fail, with `Unable to recreate undefined instance from provided data` and `Cannot read property 'total' of null`.
- MRE modifier keys applied to the `Attack` button _do_ work without error, but with a deprecation warning of `You are passing the speaker argument to the d20Roll function directly which should instead be passed as an internal key of messageData`.

Sorry I'm not able to dig deeper to find possible causes/fixes; I'm not at all familiar with the dice/item APIs yet. And of course you'll see all this when you poke around anyway, but, here's a ticket to get things started. :)

**Comment by schultzcole** [comment]
Thanks for the reports. Fortunately these seem like they'll be relatively easy to handle just looking at the descriptions, though I probably won't get around to fixing these until the weekend.

**Comment by schultzcole** [comment]
The last warning about the speaker argument is actually a core dnd5e issue with rolling attacks and damage. I should have an update with fixes for the rest of these in a little while unless I find a last minute show stopper.

**Comment by schultzcole** [comment]
Ok, these should all be fixed now in MRE 2.0.0. If you could try it out and let me know if you find any problems that'd be great.

**Comment by unsoluble** [comment]
Awesome, will test this afternoon.

**Comment by unsoluble** [comment]
I can't make anything fail in 2.0.0, so I think you've got it. :)

**Comment by schultzcole** [comment]
Woo! I'll close this issue. If you find any other problems go ahead and open a new issue.
