### ISSUE TITLE
Auto roll critical damage in specific circumstances

### ISSUE THREAD

**Issue by schultzcole** [schultzcole/FVTT-Minimal-Rolling-Enhancements-DND5E#7]
It would be reasonable to automatically roll the damage as a critical when a natrual 20 is rolled in the case where auto rolls for both checks and damage is enabled.

**Comment by trioderegion** [comment]
Only concern are the few features/items that can interact with critical hits (turning a crit into a normal hit).

I can only think of adamantine armor for this case, but it would require a non-crit damage roll.

**Comment by schultzcole** [comment]
Hmm, that is valid. I would rather have no automation than have automation that could be wrong. Then again, some might say that if a critical hit is rolled and automatic damage rolls are on, not rolling the damage as critical would be incorrect.

Both cases would require the damage to be re-rolled, but I feel the adamantine/crit cancel case is far less common. So I'm leaning towards automatically rolling damage as critical as long as both auto attacks and auto damage are enabled.

**Comment by trioderegion** [comment]
And worst case, you just roll the attack again to generate a non-crit hit. Small workaround for an extreme edge case. 👍 No complaints.

**Comment by schultzcole** [comment]
Resolved in 0.1.4
