### ISSUE TITLE
Double Rolls?

### ISSUE THREAD

**Issue by GvosRamsey** [schultzcole/FVTT-Minimal-Rolling-Enhancements-DND5E#8]
Have been looking for a replacement for Better Rolls for a bit now, but my group really prefers the double roll feature.  Is there any way to add this as an option? Thank you.

**Comment by schultzcole** [comment]
Sorry, but I don't intend on adding that feature. I also enjoyed that feature of better rolls, but personally I feel that the implementation of that feature would deviate too far from the core implementation to be within scope for this module. I'm trying to guard the scope as tightly as I can to keep it minimal. That feature was originally on my list of things to add but I had to scratch it off of the list after investigating what it would take to do.
